### ISSUE TITLE
Release: Administrative Review

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/FoundationalDataProducts#5]
This site requires an administrative review to ensure that no sensitive information is included.

**Comment by acpaquette** [comment]
- No PII

- One absolute file path found here:
https://github.com/USGS-Astrogeology/FoundationalDataProducts/blob/f2546730e5e7a05b99a876dd121fc741d32596da/make_json_bib.sh#L3

- No internal server host names or IP addresses

- No Usernames/Passwords

**Comment by jlaura** [comment]
Fixed in [05a90a7](https://github.com/USGS-Astrogeology/FoundationalDataProducts/commit/05a90a72abde2931cdde0063b9080f6563bf9234)
